### ISSUE TITLE
Spacy pipeline support

### ISSUE THREAD

**Issue by lucalazzaroni** [koenvervloesem/rasa-docker-arm#4]
I managed to use your docker image on my Raspberry Pi 4B, but since I have to switch language from English to Italian, I need Spacy that seems not to be installed in the container. How can I do that?

These are the commands suggested on Spacy's website for the installation and download of the model:
```
pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download it_core_news_sm
```

**Comment by koenvervloesem** [comment]
You're not supposed to install packages in a running container, but you could try building a Docker image with spacy in it. Have a look at the upstream Dockerfiles, for instance the one for English: https://github.com/RasaHQ/rasa/blob/main/docker/Dockerfile.pretrained_embeddings_spacy_en

**Comment by lucalazzaroni** [comment]
Ok thank you for your quick response!
